### ISSUE TITLE
bug: Not available on version 1.4.0.

### ISSUE THREAD

**Issue by kiki-kanri** [grammyjs/hydrate#24]
### Environment

- Operating System: linux(ubuntu 22.04)
- Node Version: v21.5.0
- Bun version: 1.0.20
- pnpm version: 8.13.1

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-hznhvp

Run `node index.js` to see the error.

### Describe the bug

The package cannot be used because `grammy/types` is not exported correctly.

Use nodejs, pnpm and tsx:

![image](https://github.com/grammyjs/hydrate/assets/83924639/c49703e8-442f-49f7-9c9b-f0a17aa279c3)

Use bun:

![image](https://github.com/grammyjs/hydrate/assets/83924639/600827d8-24ca-4774-bad2-7c14dabcad16)

In [`src/deps.node.ts`](https://github.com/grammyjs/hydrate/blob/eb0370e7950291ae2155b6548b25c10b997d27b9/src/deps.node.ts#L10), it originally exported @grammyjs/types, is there any special reason to replace it, or is it mainly a problem with grammY?

If it's because of grammY, I'll open a new issue over there, thanks!

**Comment by KnorpelSenf** [comment]
So far, nobody has really found out why this happens, even though a bunch of people have looked at it. There has been some discussion about it in https://t.me/grammyjs. I tried to fix it with #23 but apparently that didn't help (can you confirm?)

**Comment by kiki-kanri** [comment]
> So far, nobody has really found out why this happens, even though a bunch of people have looked at it. There has been some discussion about it in https://t.me/grammyjs. I tried to fix it with #23 but apparently that didn't help (can you confirm?)

I've confirmed that the cause is an issue with the package.js setting in the programmy package, but I'm not sure if the package should continue to use the programmy/types export or fall back to @grammyjs/types.

Looking at the error message provided by bun, the `@grammyjs/hydrate/out/deps.node.js` file is trying to export all items from `grammy/types`, but the package.json of grammy only has a type declaration file for the exports setting for types, which is causing an error when the js is introduced. This resulted in an error when the js was imported.

This can be fixed by changing the package.json settings in grammy as follows

![image](https://github.com/grammyjs/hydrate/assets/83924639/e71a9931-2f89-40c5-8707-c4be8d383dfc)

I'll open an issue in grammy.
