### ISSUE TITLE
editText with markup does not work

### ISSUE THREAD

**Issue by smatisen** [grammyjs/hydrate#7]
how to reproduce:

const statusMessage = await ctx.reply("Processing", {
    reply_markup: { remove_keyboard: true }
  });
  await statusMessage.editText("Done!");

eigher:

const statusMessage = await ctx.reply("Processing", {
    reply_markup: { remove_keyboard: true }
  });
  await statusMessage.editText("Done!",
    {
      reply_markup: { remove_keyboard: true }
    });

**Comment by KnorpelSenf** [comment]
These messages cannot be edited.

The bug in the plugin is that it does not rethrow the error correctly. I fixed it. When you update your dependencies, you'll correctly see that the API call fails as expected with the error `message can't be edited`.
